### PR TITLE
watson nlu for analysis of keywords

### PR DESCRIPTION
**Pull request by oindrillac**
## Related Issues and Dependencies
WIP Notebook on #42 

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@oindrillac looks good! Can you address the pre-commit issues that aren't fixed automatically?

```notebooks/stage/watson_keywords.ipynb#In[137]:1:1: F401 'json' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:4:1: F401 'glob' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:5:1: F401 'itertools' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:8:1: F401 'gc' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:11:1: F401 'collections.Counter' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:16:1: F401 'ibm_watson.natural_language_understanding_v1.ConceptsOptions' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:16:1: F401 'ibm_watson.natural_language_understanding_v1.EmotionOptions' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:16:1: F401 'ibm_watson.natural_language_understanding_v1.EntitiesOptions' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:16:1: F401 'ibm_watson.natural_language_understanding_v1.SentimentOptions' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:16:1: F401 'ibm_watson.natural_language_understanding_v1.CategoriesOptions' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:16:1: F401 'ibm_watson.natural_language_understanding_v1.SyntaxOptions' imported but unused
notebooks/stage/watson_keywords.ipynb#In[137]:16:1: F401 'ibm_watson.natural_language_understanding_v1.SyntaxOptionsTokens' imported but unused
notebooks/stage/watson_keywords.ipynb#In[120]:1:121: E501 line too long (132 > 120 characters)
notebooks/stage/watson_keywords.ipynb#In[123]:8:5: F841 local variable 'results_list' is assigned to but never used
notebooks/stage/watson_keywords.ipynb#In[190]:11:20: F821 undefined name 'month_keywords'
notebooks/stage/watson_keywords.ipynb#In[190]:20:29: F821 undefined name 'month'
notebooks/stage/watson_keywords.ipynb#In[202]:3:35: F821 undefined name 'Path'
```

**Comment by oindrillac** [comment]
@MichaelClifford fixed the pre-commit issues :slightly_smiling_face:

**Review by MichaelClifford — APPROVED** [review]

**Pull request merged**
